
CREATE TABLE GOODS_PROPERTY (
		  ID INT(4) NOT NULL ,
		  VALUE VARCHAR(30) NOT NULL , 
		  FK_TYPE INT(4) NOT NULL,
		  PRIMARY KEY (ID)
		  )   ; 


CREATE TABLE GOODS_PROPERTY_TYPE  (
		  ID INT(4) NOT NULL,
		  NAME VARCHAR(20) NOT NULL , 
		  FK_PARENT INT(4) NOT NULL  DEFAULT 0 , 
		  DISPLAY_NAME VARCHAR(20) , 
		  VALUE_TYPE SMALLINT NOT NULL,
		  primary Key (ID)); 