--商品分类
--服装
delete GOODS_CAT;
commit;
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('100','服装',1,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('101','运动装',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('102','女装',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('103','男装',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('104','牛仔服',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('105','童装',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('106','防寒服',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('107','毛衫',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('108','职业装',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('109','婚纱、礼服',2,'100',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('110','中老年服装',2,'100',1);

insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('120','休闲运动衫',3,'101',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('121','健身、游泳衣',3,'101',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('122','上装',3,'102',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('123','裙子',3,'102',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('124','女裤',3,'102',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('125','内衣',3,'102',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('126','女套装',3,'102',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('127','孕妇装',3,'102',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('128','男上装',3,'103',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('129','男裤',3,'103',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('130','男士内衣',3,'103',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('131','牛仔裤',3,'104',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('132','牛仔裙',3,'104',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('133','牛仔外套',3,'104',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('134','婴幼儿服饰',3,'105',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('135','儿童服装',3,'105',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('136','羽绒服',3,'106',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('137','棉服',3,'106',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('138','大衣',3,'106',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('139','男士毛衫',3,'107',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('140','女士毛衫',3,'107',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('141','外贸毛衫',3,'107',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('142','迷彩服',3,'108',1);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('143','酒店、宾馆制服',3,'108',1);
--服饰                                                  
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('200','服饰',1,'200',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('201','鞋子',2,'200',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('202','围巾、帽子',2,'200',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('203','袜子',2,'200',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('204','手套',2,'200',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('205','领带',2,'200',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('206','腰带',2,'200',2);

insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('220','男皮鞋',3,'201',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('221','女皮鞋',3,'201',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('222','凉鞋',3,'201',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('223','拖鞋',3,'201',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('224','靴子',3,'201',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('225','运动鞋',3,'201',2);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('226','童鞋',3,'201',2);
--纺织                                                  
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('300','纺织',1,'300',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('301','服装面料',2,'300',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('302','服装里料',2,'300',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('303','装饰面料',2,'300',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('304','床上用品',2,'300',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('305','毛巾',2,'300',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('306','毯子',2,'300',3);

insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('320','棉麻',3,'301',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('321','毛料',3,'301',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('322','化纤',3,'301',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('323','混纺',3,'301',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('324','服装面料其他',3,'301',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('325','窗帘布',3,'303',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('326','花边布',3,'303',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('327','装饰面料其他',3,'303',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('328','被子',3,'304',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('329','枕头、靠背',3,'304',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('330','床单、被罩、枕套',3,'304',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('331','毛毯',3,'304',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('332','席子',3,'304',3);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('333','蚊帐',3,'304',3);

--服装设备
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('400','服装设备',1,'400',4);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('401','展示道具',2,'400',4);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('402','缝纫机械',2,'400',4);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('403','洗涤整烫设备',2,'400',4);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('420','塑料人模',3,'401',4);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('421','衣架',3,'401',4);


--五金
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('500','五金',1,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('501','卫浴',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('502','水暖',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('503','轴承',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('504','模具',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('505','刀具',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('506','磨具',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('507','元件',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('508','管件',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('509','锁具',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('510','灯具',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('511','线缆',2,'500',5);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('512','配件',2,'500',5);

--小商品
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('600','小商品',1,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('601','箱包',2,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('602','小家电',2,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('603','家居用品',2,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('604','文具',2,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('605','饰品',2,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('606','工艺品',2,'600',6);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('607','玩具',2,'600',6);


--辅料
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('700','辅料',1,'700',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('701','服装辅料',2,'700',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('702','纱线',2,'700',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('720','钮扣',3,'701',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('721','拉链',3,'701',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('722','花边',3,'701',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('723','商标',3,'701',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('724','吊牌',3,'701',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('725','洗麦',3,'701',7);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('726','服装辅料其他',3,'701',7);


--商务服务
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('800','商务服务',1,'800',8);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('801','广告',2,'800',8);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('802','商标',2,'800',8);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('803','模特',2,'800',8);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('804','策划',2,'800',8);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('805','会展',2,'800',8);
insert into GOODS_CAT(TYPE_ID,TYPE_NAME,LEVELS,PARENT_ID,SHOW_ORDER) values('806','物流',2,'800',8);



commit;

--市场分类
delete market_type;
commit;
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('1','新丰鞋城','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('2','八达鞋城','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('3','招商场','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('4','小商品市场','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('5','纺交市场','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('6','凯莱女装写字楼','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('7','八达市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('8','中心布匹市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('9','南方布匹市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('10','东方市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('11','宝鼎男装写字楼','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('12','鼎顺童装','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('13','商务中心','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('14','九龙大市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('15','凯莱运动鞋广场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('16','时装中心','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('17','国际服装城','','',1);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('18','新丰羊毛衫市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('19','新金龙市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('20','鑫鑫日用品市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('22','长江床上用品市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('23','沿街市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('24','商海路沿街','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('25','招商南路沿街','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('26','商城中路沿街','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('27','新莲路沿街','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('28','万利南街、兴达市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('29','金谷市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('30','万利小商品市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('31','新丰辅料市场','','',2);
insert into market_type(MARKET_TYPE,MARKET_NAME,MARKET_GIS,MARKET_ADDRESS,SHOW_ORDER) values('32','第三停车场沿街','','',2);
commit;

--咨询分类
delete news_type;
commit;
insert into news_type(NEWS_TYPE,TYPE_NAME) values('10','商铺招租');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('20','商铺求租');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('30','市场招商');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('40','品牌招商');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('50','发 布 会');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('60','特 卖 会');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('70','招聘信息');
insert into news_type(NEWS_TYPE,TYPE_NAME) values('80','求职信息');
commit;

--定时记录
delete quartz_log;
commit;
insert into quartz_log (quartz_type,gmt_execute,quartz_memo)  values ('goods',to_date('1970-1-1','yyyy-mm-dd'),'商品定时索引');
insert into quartz_log (quartz_type,gmt_execute,quartz_memo)  values ('shop',to_date('1970-1-1','yyyy-mm-dd'),'店铺定时索引');
insert into quartz_log (quartz_type,gmt_execute,quartz_memo)  values ('member',to_date('1970-1-1','yyyy-mm-dd'),'会员定时索引');
insert into quartz_log (quartz_type,gmt_execute,quartz_memo)  values ('news',to_date('1970-1-1','yyyy-mm-dd'),'资讯定时索引');


--系统用户初始化,密码system
select seq_admin_user.nextval as id from dual;
INSERT INTO ADMIN_USER(user_id,login_name,login_password,user_STATUS,phone,gmt_create,creator,gmt_modify,modifier) 
            VALUES(1,'system','b7032734699976da705c4327718540e6','N','',sysdate,'1',sysdate,'1');

--增加推荐位置的初始化信息
delete from COMMEND_POSITION;
commit;
prompt Loading COMMEND_POSITION...
--首页商品推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'1',SEQ_COMMEND_POSITION.nextval, 'index_mid_goods', 0, '首页商品推荐1', '1', 85, 85, 256, null, '首页商品推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'1',SEQ_COMMEND_POSITION.nextval, 'index_mid_goods', 0, '首页商品推荐2', '1', 85, 85, 256, null, '首页商品推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'1',SEQ_COMMEND_POSITION.nextval, 'index_mid_goods', 0, '首页商品推荐3', '1', 85, 85, 256, null, '首页商品推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'1',SEQ_COMMEND_POSITION.nextval, 'index_mid_goods', 0, '首页商品推荐4', '1', 85, 85, 256, null, '首页商品推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'1',SEQ_COMMEND_POSITION.nextval, 'index_mid_goods', 0, '首页商品推荐5', '1', 85, 85, 256, null, '首页商品推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'1',SEQ_COMMEND_POSITION.nextval, 'index_mid_goods', 0, '首页商品推荐6', '1', 85, 85, 256, null, '首页商品推荐', sysdate, '1', sysdate, '1');

--首页店铺推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐1', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐2', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐3', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐4', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐5', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐6', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'2',SEQ_COMMEND_POSITION.nextval, 'index_bottom_shop', 0, '首页店铺推荐7', '1', 90, 110, 256, null, '首页店铺推荐', sysdate, '1', sysdate, '1');


--首页分类信息推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐1', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐2', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐3', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐4', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐5', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐6', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐7', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'3',SEQ_COMMEND_POSITION.nextval, 'index_left_commend', 0, '首页分类信息推荐8', '3', null, null, 256, null, '首页分类信息', sysdate, '1', sysdate, '1');


--分类信息首页－分类信息推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐1', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐2', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐3', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐4', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐5', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐6', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐7', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐8', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (9,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐9', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (10,'3',SEQ_COMMEND_POSITION.nextval, 'news_left_commend', 1, '分类信息首页－分类信息推荐10', '3', null, null, 256, null, '分类信息首页－分类信息推荐', sysdate, '1', sysdate, '1');


--商品首页－商品图片推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'1',SEQ_COMMEND_POSITION.nextval, 'goods_pic_commend', 2, '商品首页－商品图片推荐1', '2', 178, 49, null, '/o/200706/4028928d1357b8f2011357b8f2f70000.jpg', '商品首页－商品图片推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'1',SEQ_COMMEND_POSITION.nextval, 'goods_pic_commend', 2, '商品首页－商品图片推荐2', '2', 178, 49, null, '/o/200706/4028928d1357b8f2011357b8f2f70000.jpg', '商品首页－商品图片推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'1',SEQ_COMMEND_POSITION.nextval, 'goods_pic_commend', 2, '商品首页－商品图片推荐3', '2', 178, 49, null, '/o/200706/4028928d1357b8f2011357b8f2f70000.jpg', '商品首页－商品图片推荐', sysdate, '1', sysdate, '1');


--商品首页－最新上架商品
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品1', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品2', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品3', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品4', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品5', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品6', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品7', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品8', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (9,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品9', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (10,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品10', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (11,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品11', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (12,'1',SEQ_COMMEND_POSITION.nextval, 'goods_fresh_goods', 2, '商品首页－最新上架商品12', '3', null, null, 256, null, '商品首页－最新上架商品', sysdate, '1', sysdate, '1');


--商品首页－商品图文推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐1', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐2', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐3', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐4', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐5', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐6', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐7', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'1',SEQ_COMMEND_POSITION.nextval, 'goods_mid_goods', 2, '商品首页－商品图文推荐8', '1', 85, 85, 256, '/o/200706/4028928d1357b8f2011357ba2b190001.jpg', '商品首页－商品图文推荐', sysdate, '1', sysdate, '1');


--三维首页－店铺推荐
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐1', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐2', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐3', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐4', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐5', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐6', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐7', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐8', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (9,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐9', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (10,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐10', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (11,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐11', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (12,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐12', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (13,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐13', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (14,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐14', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (15,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐15', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (16,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐16', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (17,'2',SEQ_COMMEND_POSITION.nextval, 'gis_left_shop', 3, '三维首页－店铺推荐17', '3', null, null, 256, null, '三维首页－店铺推荐', sysdate, '1', sysdate, '1');


--商品搜索－推荐特价商品
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_special_goods', 4, '商品搜索－推荐特价商品1', '1', 80, 80, 256, '/o/200706/4028928d1357c521011357c5216f0000.jpg', '商品搜索－推荐特价商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_special_goods', 4, '商品搜索－推荐特价商品2', '1', 80, 80, 256, '/o/200706/4028928d1357c521011357c5216f0000.jpg', '商品搜索－推荐特价商品', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_special_goods', 4, '商品搜索－推荐特价商品3', '1', 80, 80, 256, '/o/200706/4028928d1357c521011357c5216f0000.jpg', '商品搜索－推荐特价商品', sysdate, '1', sysdate, '1');


insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_special_goods', 4, '商品搜索－推荐特价商品4', '1', 80, 80, 256, '/o/200706/4028928d1357c521011357c5216f0000.jpg', '商品搜索－推荐特价商品', sysdate, '1', sysdate, '1');


insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_special_goods', 4, '商品搜索－推荐特价商品5', '1', 80, 80, 256, '/o/200706/4028928d1357c521011357c5216f0000.jpg', '商品搜索－推荐特价商品', sysdate, '1', sysdate, '1');


insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_special_goods', 4, '商品搜索－推荐特价商品6', '1', 80, 80, 256, '/o/200706/4028928d1357c521011357c5216f0000.jpg', '商品搜索－推荐特价商品', sysdate, '1', sysdate, '1');



--商品搜索－热卖排行榜
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜1', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜2', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜3', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜4', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜5', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜6', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜7', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜8', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (9,'1',SEQ_COMMEND_POSITION.nextval, 'goods_search_hot_goods', 4, '商品搜索－热卖排行榜9', '3', null, null, 256, null, '商品搜索－热卖排行榜', sysdate, '1', sysdate, '1');


--店铺搜索－推荐店铺
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺1', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺2', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺3', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺4', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺5', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺6', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺7', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺8', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (9,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺9', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (10,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺10', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (11,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺11', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (12,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺12', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (13,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺13', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (14,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺14', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (15,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺15', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (16,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺16', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (17,'2',SEQ_COMMEND_POSITION.nextval, 'shop_search_left_shop', 5, '店铺搜索－推荐店铺17', '3', null, null, 256, null, '店铺搜索－推荐店铺', sysdate, '1', sysdate, '1');


--分类信息搜索－推荐分类信息
insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (1,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息1', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (2,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息2', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (3,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息3', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (4,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息4', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (5,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息5', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (6,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息6', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (7,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息7', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (8,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息8', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (9,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息9', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

insert into COMMEND_POSITION (POSITION_ORDER,COMMEND_TYPE,COMMEND_ID, COMMEND_CODE, COMMEND_PAGE, COMMEND_NAME, COMMEND_CONTENT_TYPE, PIC_WIDTH, PIC_HEIGHT, TEXT_LENGTH, PIC_PATH, REPLACE_TEXT, GMT_CREATE, CREATOR, GMT_MODIFY, MODIFIER)
values (10,'3',SEQ_COMMEND_POSITION.nextval, 'news_search_left_commend', 6, '分类信息搜索－推荐分类信息10', '3', null, null, 256, null, '分类信息搜索－推荐分类信息', sysdate, '1', sysdate, '1');

commit;